version: "3.8"

services:
  app:
    image: ashwanidevops321/lv::${BUILD_ID}
    container_name: lv_app
    volumes:
      - ./app:/var/www/html
    expose:
      - "9000"
    networks:
      - laravel_network

  nginx:
    image: nginx:alpine
    container_name: lv_nginx
    ports:
      - "8000:9090"
    volumes:
      - ./app:/var/www/html
      - ./logs:/var/log/nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
